apiVersion: v1
kind: Service
metadata:
  name: {{ include "liferay-helm.fullname" . }}-headless
  labels:
    {{- include "liferay-helm.labels" . | nindent 4 }}
spec:
  clusterIP: None # This is what makes it headless
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "liferay-helm.selectorLabels" . | nindent 4 }}
