name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "**"
      - "!docs/**"
    tags:
      - "v*"
  pull_request:
    paths:
      - "**"
      - "!docs/**"

env:
  LC_ALL: en_US.UTF-8
  PUBLISH: ${{ (github.repository == 'rotty3000/liferay-helm') && startsWith(github.ref, 'refs/tags/') && (github.event_name != 'pull_request') }}

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  ci:
    name: Build, Test, maybe Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm Installation
        shell: bash
        run: |
          helm version

      - name: Calculate Chart Version
        if: ${{ env.PUBLISH == 'true' }}
        id: calculate-chart-version
        run: |
          # This is the tag name
          echo GITHUB_REF=${{ github.ref }}

          # This is the version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest

          echo VERSION=$VERSION
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Package the Helm Chart
        if: ${{ env.PUBLISH == 'true' }}
        run: |
          helm package --version ${{ steps.calculate-chart-version.outputs.REPOSITORY }} . -d ./dist

      - name: Update Helm Index
        if: ${{ env.PUBLISH == 'true' }}
        run: |
          helm repo index ./dist
